[package]
name = "ac_interface"
version = "0.0.0"
edition = "2024"

[dependencies]
ac_db.workspace = true
ac_error.workspace = true
ac_ir.workspace = true
dashmap.workspace = true
memmap2.workspace = true
salsa.workspace = true
