[package]
name = "ac_interface"
version = "0.0.0"
edition = "2024"

[dependencies]
chumsky.workspace = true
logos.workspace = true
salsa.workspace = true

[dev-dependencies]
expect-test.workspace = true
