[workspace]
resolver = "3"
members = ["compiler/*"]

[workspace.dependencies]
# tidy-alphabetical-start
alicec_db = { path = "compiler/alicec_db" }
alicec_diag = { path = "compiler/alicec_diag" }
alicec_driver = { path = "compiler/alicec_driver" }
alicec_error = { path = "compiler/alicec_error" }
alicec_interface = { path = "compiler/alicec_interface" }
alicec_ir = { path = "compiler/alicec_ir" }
alicec_lexer = { path = "compiler/alicec_lexer" }
alicec_parser = { path = "compiler/alicec_parser" }
alicec_query = { path = "compiler/alicec_query" }
ariadne = { version = "0.5" }
clap = { version = "4" }
ctrlc = { version = "3" }
salsa = { version = "0.23" }
tracing = { version = "0.1" }
unicode-xid = { version = "0.2" }
# tidy-alphabetical-end
