[workspace]
resolver = "3"
members = ["compiler/*"]

[workspace.dependencies]
ac_ast = { path = "compiler/ac_ast" }
ac_db = { path = "compiler/ac_db" }
ac_lexer = { path = "compiler/ac_lexer" }
ac_parser = { path = "compiler/ac_parser" }
clap = { version = "4" }
ctrlc = { version = "3" }
expect-test = { version = "1" }
memchr = { version = "2" }
memmap2 = { version = "0.9" }
salsa = { version = "0.25" }
thiserror = { version = "2" }
unicode-xid = { version = "0.2" }
