[workspace]
resolver = "3"
members = ["compiler/*"]

[workspace.dependencies]
ariadne = { version = "0.6" }
chumsky = { version = "0.12" }
clap = { version = "4" }
ctrlc = { version = "3" }
logos = { version = "0.13" }
salsa = { version = "0.25" }
tracing = { version = "0.1" }
unicode-xid = { version = "0.2" }
