[workspace]
resolver = "3"
members = ["alicec"]

[workspace.dependencies]
ariadne = { version = "0.6" }
chumsky = { version = "0.12" }
clap = { version = "4" }
ctrlc = { version = "3" }
expect-test = { version = "1" }
logos = { version = "0.16" }
memmap2 = { version = "0.9" }
salsa = { version = "0.25" }
