[workspace]
resolver = "3"
members = ["compiler/*"]

[workspace.dependencies]
# tidy-alphabetical-start
alicec_db = { path = "compiler/alicec_db" }
alicec_ir = { path = "compiler/alicec_ir" }
alicec_lexer = { path = "compiler/alicec_lexer" }
alicec_parser = { path = "compiler/alicec_parser" }
ariadne = { version = "0.5" }
colored = { version = "3" }
clap = { version = "4" }
salsa = { version = "0.23" }
tracing = { version = "0.1" }
unicode-xid = { version = "0.2" }
# tidy-alphabetical-end
