[workspace]
resolver = "3"
members = ["compiler/*"]

[workspace.dependencies]
clap = { version = "4" }
ctrlc = { version = "3" }
expect-test = { version = "1" }
memchr = { version = "2" }
memmap2 = { version = "0.9" }
salsa = { version = "0.25" }
thiserror = { version = "2" }
unicode-xid = { version = "0.2" }
