[workspace]
members = ["compiler/*"]
resolver = "3"

[workspace.dependencies]
ac_db = { path = "compiler/ac_db" }
ac_driver = { path = "compiler/ac_driver" }
ac_interface = { path = "compiler/ac_interface" }
ac_lexer = { path = "compiler/ac_lexer" }
ac_parser = { path = "compiler/ac_parser" }
ac_token = { path = "compiler/ac_token" }
salsa = { version = "0.23" }
