[workspace]
members = ["compiler/*"]
resolver = "3"

[workspace.dependencies]
ac_ast = { path = "compiler/ac_ast" }
ac_cursor = { path = "compiler/ac_cursor" }
ac_db = { path = "compiler/ac_db" }
ac_driver = { path = "compiler/ac_driver" }
ac_interface = { path = "compiler/ac_interface" }
ac_lexer = { path = "compiler/ac_lexer" }
ac_parser = { path = "compiler/ac_parser" }
ac_span = { path = "compiler/ac_span" }
ac_token = { path = "compiler/ac_token" }
ariadne = { version = "0.5" }
clap = { version = "4" }
salsa = { version = "0.23" }
