[package]
name = "alicec_interface"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
alicec_db = { workspace = true }
alicec_query = { workspace = true }
# tidy-alphabetical-end
