[package]
name = "ac"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = { version = "0.5" }
clap = { version = "4", features = ["derive"] }
rayon = { version = "1" }
salsa = { version = "0.23" }

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
