[package]
name = "ac_parser"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
ac_db = { workspace = true }
ac_diagnostic = { workspace = true }
ac_lexer = { workspace = true }
ac_token = { workspace = true }
# tidy-alphabetical-end
